const ASSETS = [
  {
    sqlColumn: 'DYNCODO BZ EQUITY',
    ticker: 'DYNCODO BZ',
    shortTicker: 'DYNCODO',
    name: 'DYNAMO COUGAR FIF FIA RL',
    isBenchmark: false,
  },
  {
    sqlColumn: 'NACFFIA BZ EQUITY',
    ticker: 'NACFFIA BZ',
    shortTicker: 'NACFFIA',
    name: 'NUCLEO ACOES FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'ATMOSAC BZ EQUITY',
    ticker: 'ATMOSAC BZ',
    shortTicker: 'ATMOSAC',
    name: 'ATMOS ACOES FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'INDCAPI BZ Equity',
    ticker: 'INDCAPI BZ',
    shortTicker: 'INDCAPI',
    name: 'INDIE FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'HIXCAP BZ Equity',
    ticker: 'HIXCAP BZ',
    shortTicker: 'HIXCAP',
    name: 'HIX CPT FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'BCFIAND BZ EQUITY',
    ticker: 'BCFIAND BZ',
    shortTicker: 'BCFIAND',
    name: 'BRASIL CAPITAL FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'PERFRST BZ EQUITY',
    ticker: 'PERFRST BZ',
    shortTicker: 'PERFRST',
    name: 'PERFIN FORESIGHT FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'MSQACOE BZ EQUITY',
    ticker: 'MSQACOE BZ',
    shortTicker: 'MSQACOE',
    name: 'VELT FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'SQUALON BZ EQUITY',
    ticker: 'SQUALON BZ',
    shortTicker: 'SQUALON',
    name: 'SQUADRA LONGO ONLY FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'ABSPAR2 BZ EQUITY',
    ticker: 'ABSPAR2 BZ',
    shortTicker: 'ABSPAR2',
    name: 'ABSOLUTO PARTNERS FIC FIA II',
    isBenchmark: false,
  },
  {
    sqlColumn: '3GRFIC BZ EQUITY',
    ticker: '3GRFIC BZ',
    shortTicker: '3GRFIC',
    name: '3G RADAR FIC FIA 60',
    isBenchmark: false,
  },
  {
    sqlColumn: 'DRYBINC BZ EQUITY',
    ticker: 'DRYBINC BZ',
    shortTicker: 'DRYBINC',
    name: 'ARX INCOME FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'BOGARIV BZ EQUITY',
    ticker: 'BOGARIV BZ',
    shortTicker: 'BOGARIV',
    name: 'BOGARI VALUE FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'IPPRTAC BZ EQUITY',
    ticker: 'IPPRTAC BZ',
    shortTicker: 'IPPRTAC',
    name: 'IP PAR FIC FIA BDR NIVEL I',
    isBenchmark: false,
  },
  {
    sqlColumn: 'CONINFI BZ EQUITY',
    ticker: 'CONINFI BZ',
    shortTicker: 'CONINFI',
    name: 'CON INS FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'GUEPARD BZ EQUITY',
    ticker: 'GUEPARD BZ',
    shortTicker: 'GUEPARD',
    name: 'GUEPARDO FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'MOATFIA BZ Equity',
    ticker: 'MOATFIA BZ',
    shortTicker: 'MOATFIA',
    name: 'MOAT CPT FIC FIA A',
    isBenchmark: false,
  },
  {
    sqlColumn: 'OCEANAV BZ Equity',
    ticker: 'OCEANAV BZ',
    shortTicker: 'OCEANAV',
    name: 'OCEANA VALOR FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'ANGICOF BZ Equity',
    ticker: 'ANGICOF BZ',
    shortTicker: 'ANGICOF',
    name: 'TARPON GT FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'NAVICRK BZ Equity',
    ticker: 'NAVICRK BZ',
    shortTicker: 'NAVICRK',
    name: 'NAVI CRUISE FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'GAPEVLU BZ Equity',
    ticker: 'GAPEVLU BZ',
    shortTicker: 'GAPEVLU',
    name: 'SHARP VALUE FEEDER FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'STKLOI BZ Equity',
    ticker: 'STKLOI BZ',
    shortTicker: 'STKLOI',
    name: 'STK LONG ONLY FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'ALASFIM BZ Equity',
    ticker: 'ALASFIM BZ',
    shortTicker: 'ALASFIM',
    name: 'ALSK INSTIUTNL LONG ONLY FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'NPFUNDA BZ Equity',
    ticker: 'NPFUNDA BZ',
    shortTicker: 'NPFUNDA',
    name: 'CONSTANCIA FUNDAMENTO FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'CHRRIVR BZ Equity',
    ticker: 'CHRRIVR BZ',
    shortTicker: 'CHRRIVR',
    name: 'CHARLES RIVER FIA SUB PRINC',
    isBenchmark: false,
  },
  {
    sqlColumn: 'ALDNFIA BZ Equity',
    ticker: 'ALDNFIA BZ',
    shortTicker: 'ALDNFIA',
    name: 'ALDEN FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'ENCORAC BZ Equity',
    ticker: 'ENCORAC BZ',
    shortTicker: 'ENCORAC',
    name: 'ENCORE ACOES FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'SPXPATR BZ Equity',
    ticker: 'SPXPATR BZ',
    shortTicker: 'SPXPATR',
    name: 'SPX PATRIOT FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'SPXFALC BZ EQUITY',
    ticker: 'SPXFALC BZ',
    shortTicker: 'SPXFALC',
    name: 'SPX FALCON FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'TRUXILB BZ EQUITY',
    ticker: 'TRUXILB BZ',
    shortTicker: 'TRUXILB',
    name: 'TRUXT I LONG BIAS FIC FIM',
    isBenchmark: false,
  },
  {
    sqlColumn: 'SQUADRA BZ EQUITY',
    ticker: 'SQUADRA BZ',
    shortTicker: 'SQUADRA',
    name: 'SQUADRA LONG BIASED FI COTAS',
    isBenchmark: false,
  },
  {
    sqlColumn: 'O2FIDEA BZ EQUITY',
    ticker: 'O2FIDEA BZ',
    shortTicker: 'O2FIDEA',
    name: 'OCEANA LONG BIASED FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'NAVILBM BZ EQUITY',
    ticker: 'NAVILBM BZ',
    shortTicker: 'NAVILBM',
    name: 'NAVI LB FIC FIM',
    isBenchmark: false,
  },
  {
    sqlColumn: 'SHARPFD BZ EQUITY',
    ticker: 'SHARPFD BZ',
    shortTicker: 'SHARPFD',
    name: 'SHARP LB FEEDER FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'STKLBFF BZ EQUITY',
    ticker: 'STKLBFF BZ',
    shortTicker: 'STKLBFF',
    name: 'STK LONG BIASED FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'ENCLBFI BZ EQUITY',
    ticker: 'ENCLBFI BZ',
    shortTicker: 'ENCLBFI',
    name: 'ENCLBFI',
    isBenchmark: false,
  },
  {
    sqlColumn: 'CSH2182 BZ EQUITY',
    ticker: 'CSH2182 BZ',
    shortTicker: 'CSH2182',
    name: 'ALPHA KEY CSHG FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'BSCAPLB BZ EQUITY',
    ticker: 'BSCAPLB BZ',
    shortTicker: 'BSCAPLB',
    name: 'BRASIL CAPITAL 30 FIC FIA',
    isBenchmark: false,
  },
  {
    sqlColumn: 'BOVA11 BZ Equity',
    ticker: 'BOVA11 BZ',
    shortTicker: 'BOVA11',
    name: 'ISHARES IBOVESPA',
    isBenchmark: true,
  },
  {
    sqlColumn: 'FIAREAL BZ Equity',
    ticker: 'FIAREAL BZ',
    shortTicker: 'FIAREAL',
    name: 'REAL INV FIC FIA BDR NIVEL I',
    isBenchmark: false,
  },
  {
    sqlColumn: 'IVVB11 BZ EQUITY',
    ticker: 'IVVB11 BZ',
    shortTicker: 'IVVB11',
    name: 'ISHARES S&P 500 FIC FI IE',
    isBenchmark: true,
  },
];

const CDI_SQL_COLUMN = 'BZDIOVIN Index';

const DEFAULT_WEIGHTS = {
  return1Y: 0.15,
  return3YAnn: 0.10,
  return5YAnn: 0.05,
  sharpe1Y: 0.15,
  sharpe3Y: 0.15,
  sharpe5Y: 0.10,
  vol90D: 0.04,
  vol360D: 0.06,
  maxDrawdown3Y: 0.10,
  maxDrawdown5Y: 0.10,
};

const PORTFOLIO_WEIGHTS = {
  'DYNCODO BZ EQUITY': 0.0256039,
  'ATMOSAC BZ EQUITY': 0.0259154,
  'FIAREAL BZ Equity': 0.0677488,
  'GUEPARD BZ EQUITY': 0.0339556,
  'CSH2182 BZ EQUITY': 0.0370874,
  'SPXFALC BZ EQUITY': 0.0833266,
  'TRUXILB BZ EQUITY': 0.1215032,
  'IPPRTAC BZ EQUITY': 0.1012676,
  'BOVA11 BZ Equity': 0.0576037,
  'IVVB11 BZ EQUITY': 0.1459878,
  CASH: 0.3,
};

const HRP_WEIGHTS = {
  'IVVB11 BZ EQUITY': 0.209,
  'TRUXILB BZ EQUITY': 0.174,
  'IPPRTAC BZ EQUITY': 0.145,
  'SPXFALC BZ EQUITY': 0.119,
  'FIAREAL BZ Equity': 0.097,
  'BOVA11 BZ Equity': 0.082,
  'CSH2182 BZ EQUITY': 0.053,
  'GUEPARD BZ EQUITY': 0.049,
  'ATMOSAC BZ EQUITY': 0.037,
  'DYNCODO BZ EQUITY': 0.037,
};

const METRIC_DIRECTIONS = {
  return1Y: 'desc',
  return3YAnn: 'desc',
  return5YAnn: 'desc',
  sharpe1Y: 'desc',
  sharpe3Y: 'desc',
  sharpe5Y: 'desc',
  vol90D: 'asc',
  vol360D: 'asc',
  maxDrawdown3Y: 'desc',
  maxDrawdown5Y: 'desc',
};

module.exports = {
  ASSETS,
  CDI_SQL_COLUMN,
  DEFAULT_WEIGHTS,
  PORTFOLIO_WEIGHTS,
  HRP_WEIGHTS,
  METRIC_DIRECTIONS,
  SQL_START_DATE: '2021-01-29',
};
